name: Uno Platform Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: CloudForge.sln
      UWP_Project_Path: CloudForge.UWP\CloudForge.UWP.csproj
      Droid_Project_Path: CloudForge.Droid\CloudForge.Droid.csproj
      iOS_Project_Path: CloudForge.iOS\CloudForge.iOS.csproj
      WASM_Project_Path: CloudForge.Wasm\CloudForge.Wasm.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET 7.0.x
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Build the UWP project
    - name: Build UWP project
      run: msbuild $env:UWP_Project_Path /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build the Android project
    - name: Build Android project
      run: msbuild $env:Droid_Project_Path /t:Restore,SignAndroidPackage /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build the iOS project
    - name: Build iOS project
      run: msbuild $env:iOS_Project_Path /t:Restore,SignIosPackage /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build the WebAssembly project
    - name: Build WebAssembly project
      run: msbuild $env:WASM_Project_Path /t:Restore,SignWasmPackage /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Upload the build artifacts for each platform
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: |
          CloudForge.UWP\bin\${{ matrix.configuration }}\
          CloudForge.Droid\bin\${{ matrix.configuration }}\
          CloudForge.iOS\bin\${{ matrix.configuration }}\
          CloudForge.Wasm\bin\${{ matrix.configuration }}\
